
const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_ALERT"
const NEW_MESSAGE = "NEW_MESSAGE"
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING";
const USER_ONLINE = "USER_ONLINE";
const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEAVED = "CHAT_LEAVED"
 export {
    ALERT, 
    NEW_MESSAGE ,
     NEW_REQUEST ,
      REFETCH_CHATS, 
      NEW_ATTACHMENT,
       NEW_MESSAGE_ALERT ,
    START_TYPING ,
    STOP_TYPING,
   USER_ONLINE,
   CHAT_JOINED,
   CHAT_LEAVED


}